Public Class Cale
    Dim picture1 As Image
    Dim picture2 As Image
    Dim picture3 As Image
    Dim picture4 As Image
    Dim picture5 As Image
    Dim picture6 As Image
    Dim picture7 As Image
    Dim picture8 As Image
    Dim picture9 As Image
    Dim picture10 As Image
    Dim picture11 As Image
    Dim picture12 As Image
    Dim picture13 As Image
    Dim picture14 As Image
    Dim picture15 As Image
    Dim picture16 As Image
    Dim picture17 As Image
    Dim picture18 As Image
    Dim picture19 As Image
    Dim picture20 As Image
    Dim picture21 As Image
    Private Sub Image1_Click(sender As Object, e As EventArgs) Handles Image1.Click

    End Sub

    Private Sub ComboBox1_SelectedIndexChanged(sender As Object, e As EventArgs) Handles ComboBox1.SelectedIndexChanged
        Try
            Dim picture1 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_06000_CALES-SHIM_BOX\6100_CALES\3D\6000_E113293600.jpg") '1
            Dim picture2 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_06000_CALES-SHIM_BOX\6100_CALES\3D\6001_E113293601.jpg") '2
            Dim picture3 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_06000_CALES-SHIM_BOX\6100_CALES\3D\6002_E113293602.jpg") '3
            Dim picture4 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_06000_CALES-SHIM_BOX\6100_CALES\3D\6003_E113293603.jpg") '4
            'im picture5 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_06000_CALES-SHIM_BOX\6100_CALES\3D\6004_E113293604.jpg") '5
            Dim picture6 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_06000_CALES-SHIM_BOX\6100_CALES\3D\6005_E113293605.jpg") '6
            Dim picture7 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_06000_CALES-SHIM_BOX\6100_CALES\3D\6006_E113293606.jpg") '7
            Dim picture8 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_06000_CALES-SHIM_BOX\6100_CALES\3D\6007_E113293607.jpg") '8
            Dim picture9 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_06000_CALES-SHIM_BOX\6100_CALES\3D\6008_E113293608.jpg") '9
            Dim picture10 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_06000_CALES-SHIM_BOX\6100_CALES\3D\6009_E113293609.jpg") '10
            Dim picture11 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_06000_CALES-SHIM_BOX\6100_CALES\3D\6020_E113293620.jpg") '11
            Dim picture12 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_06000_CALES-SHIM_BOX\6100_CALES\3D\6021_E113293621.jpg") '12
            Dim picture13 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_06000_CALES-SHIM_BOX\6100_CALES\3D\6200_E140010200.jpg") '13
            Dim picture14 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_06000_CALES-SHIM_BOX\6100_CALES\3D\6201_E140010201.jpg") '14
            Dim picture15 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_06000_CALES-SHIM_BOX\6100_CALES\3D\6202_E140010202.jpg") '15
            Dim picture16 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_06000_CALES-SHIM_BOX\6100_CALES\3D\6203_E140010203.jpg") '16
            Dim picture17 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_06000_CALES-SHIM_BOX\6100_CALES\3D\6204_E140010204.jpg") '17
            Dim picture18 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_06000_CALES-SHIM_BOX\6100_CALES\3D\6205_E140010205.jpg") '18
            Dim picture19 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_06000_CALES-SHIM_BOX\6100_CALES\3D\6220_E140010206.jpg") '19
            Dim picture20 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_06000_CALES-SHIM_BOX\6100_CALES\3D\6221_E140010207.jpg") '20
            Dim picture21 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_06000_CALES-SHIM_BOX\6100_CALES\3D\CaleH.jpg") '20  
            Me.ComboBox3.Items.Clear()
            Me.ComboBox2.Items.Clear()

            'Exit Try


            ComboBox2.ResetText()
            ComboBox3.ResetText()

            Me.ComboBox2.Items.Clear()
            Me.ComboBox3.Items.Clear()
            If Me.ComboBox1.SelectedItem.ToString = "1" Then
                ComboBox2.Items.Add("12 [mm]")
                ComboBox2.Items.Add("20 [mm]")
                ComboBox2.Items.Add("50 [mm]")
            ElseIf Me.ComboBox1.SelectedItem.ToString = "2" Then
                ComboBox2.Items.Add("12 [mm]")
                ComboBox2.Items.Add("16 [mm]")
                ComboBox2.Items.Add("20 [mm]")
                ComboBox2.Items.Add("80 [mm]")
            ElseIf Me.ComboBox1.SelectedItem.ToString = "4" Then
                ComboBox2.Items.Add("50 [mm]")
                ComboBox2.Items.Add("85 [mm]")
            End If
            ComboBox1.Focus()

            With Me.ComboBox1
                Select Case ComboBox1.SelectedItem
                    Case "1"
                        Image1.Image = picture1
                    Case "2"
                        Image1.Image = picture4
                    Case "4"
                        Image1.Image = picture15
                End Select
            End With
        Catch ex As Exception

        End Try

    End Sub

    Private Sub Button2_Click(sender As Object, e As EventArgs) Handles Button2.Click
        Parcatipi.Show()
        Me.Close()
    End Sub

    Private Sub Shim_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        ComboBox1.Items.Add("1")
        ComboBox1.Items.Add("2")
        ComboBox1.Items.Add("4")
        TextBox1.Text = My.Settings.Uyari

    End Sub

    Private Sub ComboBox2_SelectedIndexChanged(sender As Object, e As EventArgs) Handles ComboBox2.SelectedIndexChanged
        Try
            Dim picture1 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_06000_CALES-SHIM_BOX\6100_CALES\3D\6000_E113293600.jpg") '1
            Dim picture2 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_06000_CALES-SHIM_BOX\6100_CALES\3D\6001_E113293601.jpg") '2
            Dim picture3 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_06000_CALES-SHIM_BOX\6100_CALES\3D\6002_E113293602.jpg") '3
            Dim picture4 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_06000_CALES-SHIM_BOX\6100_CALES\3D\6003_E113293603.jpg") '4
            ' Dim picture5 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_06000_CALES-SHIM_BOX\6100_CALES\3D\6004_E113293604.jpg") '5
            Dim picture6 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_06000_CALES-SHIM_BOX\6100_CALES\3D\6005_E113293605.jpg") '6
            Dim picture7 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_06000_CALES-SHIM_BOX\6100_CALES\3D\6006_E113293606.jpg") '7
            Dim picture8 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_06000_CALES-SHIM_BOX\6100_CALES\3D\6007_E113293607.jpg") '8
            Dim picture9 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_06000_CALES-SHIM_BOX\6100_CALES\3D\6008_E113293608.jpg") '9
            Dim picture10 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_06000_CALES-SHIM_BOX\6100_CALES\3D\6009_E113293609.jpg") '10
            Dim picture11 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_06000_CALES-SHIM_BOX\6100_CALES\3D\6020_E113293620.jpg") '11
            Dim picture12 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_06000_CALES-SHIM_BOX\6100_CALES\3D\6021_E113293621.jpg") '12
            Dim picture13 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_06000_CALES-SHIM_BOX\6100_CALES\3D\6200_E140010200.jpg") '13
            Dim picture14 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_06000_CALES-SHIM_BOX\6100_CALES\3D\6201_E140010201.jpg") '14
            Dim picture15 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_06000_CALES-SHIM_BOX\6100_CALES\3D\6202_E140010202.jpg") '15
            Dim picture16 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_06000_CALES-SHIM_BOX\6100_CALES\3D\6203_E140010203.jpg") '16
            Dim picture17 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_06000_CALES-SHIM_BOX\6100_CALES\3D\6204_E140010204.jpg") '17
            Dim picture18 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_06000_CALES-SHIM_BOX\6100_CALES\3D\6205_E140010205.jpg") '18
            Dim picture19 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_06000_CALES-SHIM_BOX\6100_CALES\3D\6220_E140010206.jpg") '19
            Dim picture20 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_06000_CALES-SHIM_BOX\6100_CALES\3D\6221_E140010207.jpg") '20            Me.ComboBox3.Items.Clear()
            Dim picture21 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_06000_CALES-SHIM_BOX\6100_CALES\3D\CaleH.jpg") '20        
            'Me.ComboBox3.Items.Clear()

            'Exit Try

            Me.ComboBox3.Items.Clear()

            ComboBox3.ResetText()
            If ComboBox1.SelectedItem.ToString = "1" Then
                If Me.ComboBox2.SelectedItem.ToString = "50 [mm]" Then
                    ComboBox3.Items.Add("Geometri")
                ElseIf ComboBox2.SelectedItem = "20 [mm]" Then
                    ComboBox3.Items.Add("İmalatçı")
                    ComboBox3.Items.Add("Geometri")
                ElseIf ComboBox2.SelectedItem = "12 [mm]" Then
                    ComboBox3.Items.Add("İmalatçı")
                    ComboBox3.Items.Add("Geometri")
                End If
            End If
            If ComboBox1.SelectedItem.ToString = "2" Then
                If ComboBox2.SelectedItem = "12 [mm]" Then
                    ComboBox3.Items.Add("İmalatçı")
                    ComboBox3.Items.Add("Geometri")
                ElseIf ComboBox2.SelectedItem = "16 [mm]" Then
                    ComboBox3.Items.Add("İmalatçı")
                    ComboBox3.Items.Add("Geometri")
                ElseIf ComboBox2.SelectedItem = "20 [mm]" Then
                    ComboBox3.Items.Add("İmalatçı")
                    ComboBox3.Items.Add("Geometri")
                ElseIf Me.ComboBox2.SelectedItem.ToString = "80 [mm]" Then
                    ComboBox3.Items.Add("İmalatçı")
                End If
            End If
            If Me.ComboBox1.SelectedItem.ToString = "4" Then
                If Me.ComboBox2.SelectedItem.ToString = "85 [mm]" Then
                    ComboBox3.Items.Add("İmalatçı")
                ElseIf Me.ComboBox2.SelectedItem.ToString = "50 [mm]" Then
                    ComboBox3.Items.Add("İmalatçı")
                End If
            End If
            ComboBox2.Focus()
            With Me.ComboBox2
                Select Case ComboBox1.SelectedItem
                    Case "1"
                        If ComboBox2.SelectedItem = "12 [mm]" Then
                            Image1.Image = picture21
                        ElseIf ComboBox2.SelectedItem = "20 [mm]" Then
                            Image1.Image = picture21
                        ElseIf ComboBox2.SelectedItem = "50 [mm]" Then
                            Image1.Image = picture21
                        End If
                    Case "2"
                        If ComboBox2.SelectedItem = "12 [mm]" Then
                            Image1.Image = picture21
                        ElseIf ComboBox2.SelectedItem = "16 [mm]" Then
                            Image1.Image = picture21
                        ElseIf ComboBox2.SelectedItem = "20 [mm]" Then
                            Image1.Image = picture21
                        ElseIf ComboBox2.SelectedItem = "80 [mm]" Then
                            Image1.Image = picture21
                        End If
                    Case "4"
                        If ComboBox2.SelectedItem = "50 [mm]" Then
                            Image1.Image = picture21
                        ElseIf ComboBox2.SelectedItem = "85 [mm]" Then
                            Image1.Image = picture21
                        End If

                End Select
            End With
        Catch ex As Exception

        End Try
    End Sub

    Private Sub ComboBox3_SelectedIndexChanged(sender As Object, e As EventArgs) Handles ComboBox3.SelectedIndexChanged
        Try
            Dim picture1 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_06000_CALES-SHIM_BOX\6100_CALES\3D\6000_E113293600.jpg") '1
            Dim picture2 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_06000_CALES-SHIM_BOX\6100_CALES\3D\6001_E113293601.jpg") '2
            Dim picture3 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_06000_CALES-SHIM_BOX\6100_CALES\3D\6002_E113293602.jpg") '3
            Dim picture4 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_06000_CALES-SHIM_BOX\6100_CALES\3D\6003_E113293603.jpg") '4
            ' Dim picture5 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_06000_CALES-SHIM_BOX\6100_CALES\3D\6004_E113293604.jpg") '5
            Dim picture6 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_06000_CALES-SHIM_BOX\6100_CALES\3D\6005_E113293605.jpg") '6
            Dim picture7 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_06000_CALES-SHIM_BOX\6100_CALES\3D\6006_E113293606.jpg") '7
            Dim picture8 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_06000_CALES-SHIM_BOX\6100_CALES\3D\6007_E113293607.jpg") '8
            Dim picture9 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_06000_CALES-SHIM_BOX\6100_CALES\3D\6008_E113293608.jpg") '9
            Dim picture10 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_06000_CALES-SHIM_BOX\6100_CALES\3D\6009_E113293609.jpg") '10
            Dim picture11 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_06000_CALES-SHIM_BOX\6100_CALES\3D\6020_E113293620.jpg") '11
            Dim picture12 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_06000_CALES-SHIM_BOX\6100_CALES\3D\6021_E113293621.jpg") '12
            Dim picture13 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_06000_CALES-SHIM_BOX\6100_CALES\3D\6200_E140010200.jpg") '13
            Dim picture14 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_06000_CALES-SHIM_BOX\6100_CALES\3D\6201_E140010201.jpg") '14
            Dim picture15 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_06000_CALES-SHIM_BOX\6100_CALES\3D\6202_E140010202.jpg") '15
            Dim picture16 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_06000_CALES-SHIM_BOX\6100_CALES\3D\6203_E140010203.jpg") '16
            Dim picture17 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_06000_CALES-SHIM_BOX\6100_CALES\3D\6204_E140010204.jpg") '17
            Dim picture18 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_06000_CALES-SHIM_BOX\6100_CALES\3D\6205_E140010205.jpg") '18
            Dim picture19 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_06000_CALES-SHIM_BOX\6100_CALES\3D\6220_E140010206.jpg") '19
            Dim picture20 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_06000_CALES-SHIM_BOX\6100_CALES\3D\6221_E140010207.jpg") '20
            Dim picture21 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_06000_CALES-SHIM_BOX\6100_CALES\3D\CaleH.jpg") '20            Me.ComboBox3.Items.Clear()


            ComboBox3.Focus()
            With Me.ComboBox3
                Select Case ComboBox1.SelectedItem
                    Case "1"
                        If ComboBox2.SelectedItem = "12 [mm]" Then
                            If ComboBox3.SelectedItem = "Geometri" Then
                                Image1.Image = picture19
                            Else
                                Image1.Image = picture11
                            End If
                        ElseIf ComboBox2.SelectedItem = "20 [mm]" Then
                            If ComboBox3.SelectedItem = "Geometri" Then
                                Image1.Image = picture2
                                'Image1.Image = picture4
                            Else
                                Image1.Image = picture1
                            End If
                        ElseIf ComboBox2.SelectedItem = "50 [mm]" Then
                            Image1.Image = picture13
                        End If
                    Case "2"
                        If ComboBox2.SelectedItem = "12 [mm]" Then
                            If ComboBox3.SelectedItem = "Geometri" Then
                                Image1.Image = picture20
                            Else
                                Image1.Image = picture12
                            End If
                        ElseIf ComboBox2.SelectedItem = "16 [mm]" Then
                            If ComboBox3.SelectedItem = "Geometri" Then
                                Image1.Image = picture10
                            Else
                                Image1.Image = picture9
                            End If
                        ElseIf ComboBox2.SelectedItem = "20 [mm]" Then
                            If ComboBox3.SelectedItem = "Geometri" Then
                                Image1.Image = picture4
                            Else
                                Image1.Image = picture3
                            End If
                        ElseIf ComboBox2.SelectedItem = "80 [mm]" Then
                            If ComboBox3.SelectedItem = "Geometri" Then
                                Image1.Image = picture6
                            End If
                        End If

                    Case "4"
                        If ComboBox2.SelectedItem = "50 [mm]" Then
                            If ComboBox3.SelectedItem = "Geometri" Then
                                Image1.Image = picture18
                            End If
                        ElseIf ComboBox2.SelectedItem = "85 [mm]" Then
                            If ComboBox3.SelectedItem = "Geometri" Then
                                Image1.Image = picture15
                                'Image1.Image = picture15
                            End If
                        End If
                End Select
            End With
        Catch ex As Exception


        End Try
    End Sub

    Private Sub Button1_Click(sender As Object, e As EventArgs) Handles Button1.Click
        Dim CATIA As Object
        Dim Mydocument
        Dim PartFactory
        Dim iPartDoc
        Select Case ComboBox1.SelectedItem
            Case "1"
                If ComboBox2.SelectedItem = "12 [mm]" Then
                    If ComboBox3.SelectedItem = "Geometri" Then
                        'Get CATIA Or Launch it if necessary.
                        On Error Resume Next
                        CATIA = GetObject(, "CATIA.Application")

                        CATIA = CreateObject("CATIA.Application")
                        CATIA.Visible = True
                        iPartDoc = CATIA.Documents.Open("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_06000_CALES-SHIM_BOX\6100_CALES\3D\6220_SUPPLIER_SHIM_3_(12)_th5.CATPart")

                        On Error GoTo 0
                        ' Add a new Part


                        'PartFactory = Mydocument.Part.ShapeFactory  ' Retrieve the Part Factory.
                    Else
                        'Get CATIA Or Launch it if necessary.
                        On Error Resume Next
                        CATIA = GetObject(, "CATIA.Application")

                        CATIA = CreateObject("CATIA.Application")
                        CATIA.Visible = True
                        iPartDoc = CATIA.Documents.Open("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_06000_CALES-SHIM_BOX\6100_CALES\3D\6020_SHIM_3_(12)_th5.CATPart")

                        On Error GoTo 0
                        ' Add a new Part 


                        'PartFactory = Mydocument.Part.ShapeFactory  ' Retrieve the Part Factory.
                    End If
                ElseIf ComboBox2.SelectedItem = "20 [mm]" Then
                    If ComboBox3.SelectedItem = "Geometri" Then
                        'Get CATIA Or Launch it if necessary.
                        On Error Resume Next
                        CATIA = GetObject(, "CATIA.Application")

                        CATIA = CreateObject("CATIA.Application")
                        CATIA.Visible = True
                        iPartDoc = CATIA.Documents.Open("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_06000_CALES-SHIM_BOX\6100_CALES\3D\6001_SUPPLIER_SHIM_3.CATPart")

                        On Error GoTo 0
                        ' Add a new Part


                        'PartFactory = Mydocument.Part.ShapeFactory  ' Retrieve the Part Factory.
                        '''Image1.Image = picture4
                    Else
                        'Get CATIA Or Launch it if necessary.
                        On Error Resume Next
                        CATIA = GetObject(, "CATIA.Application")

                        CATIA = CreateObject("CATIA.Application")
                        CATIA.Visible = True
                        iPartDoc = CATIA.Documents.Open("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_06000_CALES-SHIM_BOX\6100_CALES\3D\6000_SHIM_3_th5.CATPart")

                        On Error GoTo 0
                        ' Add a new Part


                        'PartFactory = Mydocument.Part.ShapeFactory  ' Retrieve the Part Factory.
                    End If
                ElseIf ComboBox2.SelectedItem = "50 [mm]" Then
                    'Get CATIA Or Launch it if necessary.
                    On Error Resume Next
                    CATIA = GetObject(, "CATIA.Application")

                    CATIA = CreateObject("CATIA.Application")
                    CATIA.Visible = True
                    iPartDoc = CATIA.Documents.Open("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_06000_CALES-SHIM_BOX\6100_CALES\3D\6200_SHIM_PMF_32.CATPart")

                    On Error GoTo 0
                    ' Add a new Part


                    'PartFactory = Mydocument.Part.ShapeFactory  ' Retrieve the Part Factory.
                End If
            Case "2"
                If ComboBox2.SelectedItem = "12 [mm]" Then
                    If ComboBox3.SelectedItem = "Geometri" Then
                        'Get CATIA Or Launch it if necessary.
                        On Error Resume Next
                        CATIA = GetObject(, "CATIA.Application")

                        CATIA = CreateObject("CATIA.Application")
                        CATIA.Visible = True
                        iPartDoc = CATIA.Documents.Open("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_06000_CALES-SHIM_BOX\6100_CALES\3D\6221_SUPPLIER_SHIM_4_(12)_th5.CATPart")

                        On Error GoTo 0
                        ' Add a new Part


                        'PartFactory = Mydocument.Part.ShapeFactory  ' Retrieve the Part Factory.
                    Else
                        'Get CATIA Or Launch it if necessary.
                        On Error Resume Next
                        CATIA = GetObject(, "CATIA.Application")

                        CATIA = CreateObject("CATIA.Application")
                        CATIA.Visible = True
                        iPartDoc = CATIA.Documents.Open("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_06000_CALES-SHIM_BOX\6100_CALES\3D\6021_SHIM_4_(12)_th5.CATPart")

                        On Error GoTo 0
                        ' Add a new Part


                        'PartFactory = Mydocument.Part.ShapeFactory  ' Retrieve the Part Factory.
                    End If
                ElseIf ComboBox2.SelectedItem = "16 [mm]" Then
                    If ComboBox3.SelectedItem = "Geometri" Then
                        'Get CATIA Or Launch it if necessary.
                        On Error Resume Next
                        CATIA = GetObject(, "CATIA.Application")

                        CATIA = CreateObject("CATIA.Application")
                        CATIA.Visible = True
                        iPartDoc = CATIA.Documents.Open("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_06000_CALES-SHIM_BOX\6100_CALES\3D\6009_SUPPLIER_SHIM_SERRAGE_40.CATPart")

                        On Error GoTo 0
                        ' Add a new Part


                        'PartFactory = Mydocument.Part.ShapeFactory  ' Retrieve the Part Factory.
                    Else
                        'Get CATIA Or Launch it if necessary.
                        On Error Resume Next
                        CATIA = GetObject(, "CATIA.Application")

                        CATIA = CreateObject("CATIA.Application")
                        CATIA.Visible = True
                        iPartDoc = CATIA.Documents.Open("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_06000_CALES-SHIM_BOX\6100_CALES\3D\6008_SHIM_SERRAGE_40.CATPart")

                        On Error GoTo 0
                        ' Add a new Part


                        'PartFactory = Mydocument.Part.ShapeFactory  ' Retrieve the Part Factory.
                    End If
                ElseIf ComboBox2.SelectedItem = "20 [mm]" Then
                    If ComboBox3.SelectedItem = "Geometri" Then
                        'Get CATIA Or Launch it if necessary.
                        On Error Resume Next
                        CATIA = GetObject(, "CATIA.Application")

                        CATIA = CreateObject("CATIA.Application")
                        CATIA.Visible = True
                        iPartDoc = CATIA.Documents.Open("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_06000_CALES-SHIM_BOX\6100_CALES\3D\6003_SUPPLIER_SHIM_4.CATPart")

                        On Error GoTo 0
                        ' Add a new Part


                        'PartFactory = Mydocument.Part.ShapeFactory  ' Retrieve the Part Factory.
                    Else
                        'Get CATIA Or Launch it if necessary.
                        On Error Resume Next
                        CATIA = GetObject(, "CATIA.Application")

                        CATIA = CreateObject("CATIA.Application")
                        CATIA.Visible = True
                        iPartDoc = CATIA.Documents.Open("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_06000_CALES-SHIM_BOX\6100_CALES\3D\6001_SUPPLIER_SHIM_3.CATPart")

                        On Error GoTo 0
                        ' Add a new Part


                        'PartFactory = Mydocument.Part.ShapeFactory  ' Retrieve the Part Factory.
                    End If
                ElseIf ComboBox2.SelectedItem = "80 [mm]" Then
                    If ComboBox3.SelectedItem = "Geometri" Then
                        'Get CATIA Or Launch it if necessary.
                        On Error Resume Next
                        CATIA = GetObject(, "CATIA.Application")

                        CATIA = CreateObject("CATIA.Application")
                        CATIA.Visible = True
                        iPartDoc = CATIA.Documents.Open("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_06000_CALES-SHIM_BOX\6100_CALES\3D\6005_SUPPLIER_SHIM_PMF.CATPart")

                        On Error GoTo 0
                        ' Add a new Part


                        'PartFactory = Mydocument.Part.ShapeFactory  ' Retrieve the Part Factory.
                    End If
                End If

            Case "4"
                If ComboBox2.SelectedItem = "50 [mm]" Then
                    If ComboBox3.SelectedItem = "Geometri" Then
                        'Get CATIA Or Launch it if necessary.
                        On Error Resume Next
                        CATIA = GetObject(, "CATIA.Application")

                        CATIA = CreateObject("CATIA.Application")
                        CATIA.Visible = True
                        iPartDoc = CATIA.Documents.Open("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_06000_CALES-SHIM_BOX\6100_CALES\3D\6205_SUPPLIER_SHIM_PMF_32.CATPart")

                        On Error GoTo 0
                        ' Add a new Part


                        'PartFactory = Mydocument.Part.ShapeFactory  ' Retrieve the Part Factory.
                    End If
                ElseIf ComboBox2.SelectedItem = "85 [mm]" Then
                    If ComboBox3.SelectedItem = "Geometri" Then
                        'Get CATIA Or Launch it if necessary.
                        On Error Resume Next
                        CATIA = GetObject(, "CATIA.Application")

                        CATIA = CreateObject("CATIA.Application")
                        CATIA.Visible = True
                        iPartDoc = CATIA.Documents.Open("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_06000_CALES-SHIM_BOX\6100_CALES\3D\6202_SHIM_Poteau_02.CATPart")

                        On Error GoTo 0
                        ' Add a new Part


                        'PartFactory = Mydocument.Part.ShapeFactory  ' Retrieve the Part Factory.
                        '''Image1.Image = picture15
                    End If
                End If
        End Select
    End Sub

    Private Sub Button5_Click(sender As Object, e As EventArgs) Handles Button5.Click
        RenaultStandardi.Show()
        Me.Close()
    End Sub

    Private Sub TextBox1_TextChanged(sender As Object, e As EventArgs)

    End Sub

    Private Sub Button4_Click(sender As Object, e As EventArgs) Handles Button4.Click
        My.Settings.Uyari = TextBox1.Text

    End Sub
End Class