Public Class Poteau
    Dim picture1 As Image
    Dim picture2 As Image
    Dim picture3 As Image
    Dim picture4 As Image
    Dim picture5 As Image
    Dim picture6 As Image
    Dim picture7 As Image
    Dim picture8 As Image
    Dim picture9 As Image
    Dim picture10 As Image
    Dim picture11 As Image
    Dim picture12 As Image
    Dim picture13 As Image
    Dim picture14 As Image
    Dim picture15 As Image
    Dim picture16 As Image
    Dim picture17 As Image
    Dim picture18 As Image
    Dim picture19 As Image
    Dim picture20 As Image
    Dim picture21 As Image
    Dim picture22 As Image
    Dim picture23 As Image
    Dim picture24 As Image
    Dim picture25 As Image
    Dim picture26 As Image
    Dim picture27 As Image
    Dim picture28 As Image
    Dim picture29 As Image
    Dim picture30 As Image
    Dim picture31 As Image
    Dim picture32 As Image
    Dim picture33 As Image
    Dim picture34 As Image
    Dim picture35 As Image
    Dim picture36 As Image
    Dim picture37 As Image
    Dim picture38 As Image
    Private Sub ComboBox1_SelectedIndexChanged(sender As Object, e As EventArgs) Handles ComboBox1.SelectedIndexChanged
        Try
            Dim picture1 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\10_STOOL\3D\1000_JW_STOOL_H100\1000.png") '1
            'Dim picture2 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\10_STOOL\3D\1001_JW_STOOL_H150\1001.png") '2
            'Dim picture3 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\10_STOOL\3D\1002_JW_STOOL_H200\1002.png") '3
            'Dim picture4 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\10_STOOL\3D\1003_JW_STOOL_H250\1003.png") '4
            'Dim picture5 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\10_STOOL\3D\1004_JW_STOOL_H300\1004.png") '5
            'Dim picture6 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\10_STOOL\3D\1005_JW_STOOL_H350\1005.png") '6
            'Dim picture7 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\10_STOOL\3D\1006_JW_STOOL_H400\1006.png") '7
            'Dim picture8 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\10_STOOL\3D\1007_JW_STOOL_H450\1007.png") '8
            'Dim picture9 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\10_STOOL\3D\1008_JW_STOOL_H500\1008.png") '9
            Dim picture10 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\11_STOOL_avec_isolation\3D\1100_JW_STOOL_H100\1100.png") '10
            'Dim picture11 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\11_STOOL_avec_isolation\3D\1100_JW_STOOL_H100\1101.png") '11
            'Dim picture12 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\11_STOOL_avec_isolation\3D\1100_JW_STOOL_H100\1102.png") '12
            'Dim picture13 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\11_STOOL_avec_isolation\3D\1100_JW_STOOL_H100\1103.png") '13
            'Dim picture14 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\11_STOOL_avec_isolation\3D\1100_JW_STOOL_H100\1104.png") '14
            'Dim picture15 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\11_STOOL_avec_isolation\3D\1100_JW_STOOL_H100\1105.png") '15
            'Dim picture16 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\11_STOOL_avec_isolation\3D\1100_JW_STOOL_H100\1106.png") '16
            'Dim picture17 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\11_STOOL_avec_isolation\3D\1100_JW_STOOL_H100\1107.png") '17
            'Dim picture18 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\11_STOOL_avec_isolation\3D\1100_JW_STOOL_H100\1108.png") '18
            Dim picture19 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\12_STOOL_sans_thread\3D\1200_JW_STOOL_H100\1200.png") '19
            'Dim picture20 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\12_STOOL_sans_thread\3D\1200_JW_STOOL_H100\1201.png") '20
            'Dim picture21 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\12_STOOL_sans_thread\3D\1200_JW_STOOL_H100\1202.png") '21
            'Dim picture22 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\12_STOOL_sans_thread\3D\1200_JW_STOOL_H100\1203.png") '22
            'Dim picture23 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\12_STOOL_sans_thread\3D\1200_JW_STOOL_H100\1204.png") '23
            'Dim picture24 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\12_STOOL_sans_thread\3D\1200_JW_STOOL_H100\1205.png") '24
            'Dim picture25 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\12_STOOL_sans_thread\3D\1200_JW_STOOL_H100\1206.png") '25
            'Dim picture26 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\12_STOOL_sans_thread\3D\1200_JW_STOOL_H100\1207.png") '26
            'Dim picture27 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\12_STOOL_sans_thread\3D\1200_JW_STOOL_H100\1208.png") '27
            Dim picture28 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\13_STOOL_avec_isolation_sans_thread\3D\1300_JW_STOOL_H100\1300.png") '28
            'Dim picture29 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\13_STOOL_avec_isolation_sans_thread\3D\1300_JW_STOOL_H100\1301.png") '29
            'Dim picture30 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\13_STOOL_avec_isolation_sans_thread\3D\1300_JW_STOOL_H100\1302.png") '30
            'Dim picture31 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\13_STOOL_avec_isolation_sans_thread\3D\1300_JW_STOOL_H100\1303.png") '31
            'Dim picture32 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\13_STOOL_avec_isolation_sans_thread\3D\1300_JW_STOOL_H100\1304.png") '32
            'Dim picture33 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\13_STOOL_avec_isolation_sans_thread\3D\1300_JW_STOOL_H100\1305.png") '33
            'Dim picture34 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\13_STOOL_avec_isolation_sans_thread\3D\1300_JW_STOOL_H100\1306.png") '34
            'Dim picture35 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\13_STOOL_avec_isolation_sans_thread\3D\1300_JW_STOOL_H100\1307.png") '35
            'Dim picture36 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\13_STOOL_avec_isolation_sans_thread\3D\1300_JW_STOOL_H100\1308.png") '36
            'Dim picture37 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\20_PACK ISOLATION_insulation set\3D\ISOLATION_POTEAU.png") '37
            'Dim picture38 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\12_STOOL_sans_thread.jpg") '38
            ComboBox1.Focus()
            ComboBox2.ResetText()
            ComboBox3.ResetText()
            Image1.Image = picture1
            'With Me.ComboBox1
            '    Select Case ComboBox1.SelectedItem
            '        Case "100 [mm]"
            '            Image1.Image = picture1
            '            'Case "150 [mm]"
            '            '    Image1.Image = picture2
            '            'Case "200 [mm]"
            '            '    Image1.Image = picture3
            '            'Case "250 [mm]"
            '            '    Image1.Image = picture4
            '            'Case "300 [mm]"
            '            '    Image1.Image = picture5
            '            'Case "350 [mm]"
            '            '    Image1.Image = picture6
            '            'Case "400 [mm]"
            '            '    Image1.Image = picture7
            '            'Case "450 [mm]"
            '            '    Image1.Image = picture8
            '            'Case "500 [mm]"
            '            '    Image1.Image = picture9
            '    End Select
            'End With
        Catch ex As Exception

        End Try
    End Sub

    Private Sub ComboBox2_SelectedIndexChanged(sender As Object, e As EventArgs) Handles ComboBox2.SelectedIndexChanged
        Try
            Dim picture1 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\10_STOOL\3D\1000_JW_STOOL_H100\1000.png") '1
            'Dim picture2 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\10_STOOL\3D\1001_JW_STOOL_H150\1001.png") '2
            'Dim picture3 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\10_STOOL\3D\1002_JW_STOOL_H200\1002.png") '3
            'Dim picture4 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\10_STOOL\3D\1003_JW_STOOL_H250\1003.png") '4
            'Dim picture5 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\10_STOOL\3D\1004_JW_STOOL_H300\1004.png") '5
            'Dim picture6 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\10_STOOL\3D\1005_JW_STOOL_H350\1005.png") '6
            'Dim picture7 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\10_STOOL\3D\1006_JW_STOOL_H400\1006.png") '7
            'Dim picture8 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\10_STOOL\3D\1007_JW_STOOL_H450\1007.png") '8
            'Dim picture9 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\10_STOOL\3D\1008_JW_STOOL_H500\1008.png") '9
            Dim picture10 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\11_STOOL_avec_isolation\3D\1100_JW_STOOL_H100\1100.png") '10
            'Dim picture11 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\11_STOOL_avec_isolation\3D\1100_JW_STOOL_H100\1101.png") '11
            'Dim picture12 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\11_STOOL_avec_isolation\3D\1100_JW_STOOL_H100\1102.png") '12
            'Dim picture13 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\11_STOOL_avec_isolation\3D\1100_JW_STOOL_H100\1103.png") '13
            'Dim picture14 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\11_STOOL_avec_isolation\3D\1100_JW_STOOL_H100\1104.png") '14
            'Dim picture15 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\11_STOOL_avec_isolation\3D\1100_JW_STOOL_H100\1105.png") '15
            'Dim picture16 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\11_STOOL_avec_isolation\3D\1100_JW_STOOL_H100\1106.png") '16
            'Dim picture17 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\11_STOOL_avec_isolation\3D\1100_JW_STOOL_H100\1107.png") '17
            'Dim picture18 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\11_STOOL_avec_isolation\3D\1100_JW_STOOL_H100\1108.png") '18
            Dim picture19 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\12_STOOL_sans_thread\3D\1200_JW_STOOL_H100\1200.png") '19
            'Dim picture20 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\12_STOOL_sans_thread\3D\1200_JW_STOOL_H100\1201.png") '20
            'Dim picture21 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\12_STOOL_sans_thread\3D\1200_JW_STOOL_H100\1202.png") '21
            'Dim picture22 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\12_STOOL_sans_thread\3D\1200_JW_STOOL_H100\1203.png") '22
            'Dim picture23 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\12_STOOL_sans_thread\3D\1200_JW_STOOL_H100\1204.png") '23
            'Dim picture24 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\12_STOOL_sans_thread\3D\1200_JW_STOOL_H100\1205.png") '24
            'Dim picture25 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\12_STOOL_sans_thread\3D\1200_JW_STOOL_H100\1206.png") '25
            'Dim picture26 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\12_STOOL_sans_thread\3D\1200_JW_STOOL_H100\1207.png") '26
            'Dim picture27 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\12_STOOL_sans_thread\3D\1200_JW_STOOL_H100\1208.png") '27
            Dim picture28 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\13_STOOL_avec_isolation_sans_thread\3D\1300_JW_STOOL_H100\1300.png") '28
            'Dim picture29 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\13_STOOL_avec_isolation_sans_thread\3D\1300_JW_STOOL_H100\1301.png") '29
            'Dim picture30 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\13_STOOL_avec_isolation_sans_thread\3D\1300_JW_STOOL_H100\1302.png") '30
            'Dim picture31 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\13_STOOL_avec_isolation_sans_thread\3D\1300_JW_STOOL_H100\1303.png") '31
            'Dim picture32 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\13_STOOL_avec_isolation_sans_thread\3D\1300_JW_STOOL_H100\1304.png") '32
            'Dim picture33 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\13_STOOL_avec_isolation_sans_thread\3D\1300_JW_STOOL_H100\1305.png") '33
            'Dim picture34 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\13_STOOL_avec_isolation_sans_thread\3D\1300_JW_STOOL_H100\1306.png") '34
            'Dim picture35 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\13_STOOL_avec_isolation_sans_thread\3D\1300_JW_STOOL_H100\1307.png") '35
            'Dim picture36 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\13_STOOL_avec_isolation_sans_thread\3D\1300_JW_STOOL_H100\1308.png") '36
            'Dim picture37 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\20_PACK ISOLATION_insulation set\3D\ISOLATION_POTEAU.png") '37
            'Dim picture38 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\12_STOOL_sans_thread.jpg") '38
            'Dim picture37 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\20_PACK ISOLATION_insulation set\3D\ISOLATION_POTEAU.png") '37
            ' Dim picture38 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\12_STOOL_sans_thread.jpg") '38
            ComboBox2.Focus()
            ComboBox3.ResetText()

            With Me.ComboBox2
                'Select Case ComboBox1.SelectedItem
                '    Case "100 [mm]"
                If ComboBox2.SelectedItem = "Boş" Then
                    Image1.Image = picture28
                ElseIf ComboBox2.SelectedItem = "Dişli" Then
                    Image1.Image = picture10
                    '        End If
                    '    Case "150 [mm]"
                    '        If ComboBox2.SelectedItem = "Boş" Then
                    '            Image1.Image = picture29
                    '        ElseIf ComboBox2.SelectedItem = "Dişli" Then
                    '            Image1.Image = picture2
                    '        End If

                    '    Case "200 [mm]"
                    '        If ComboBox2.SelectedItem = "Boş" Then
                    '            Image1.Image = picture30
                    '        ElseIf ComboBox2.SelectedItem = "Dişli" Then
                    '            Image1.Image = picture12
                    '        End If
                    '    Case "250 [mm]"
                    '        If ComboBox2.SelectedItem = "Boş" Then
                    '            Image1.Image = picture31
                    '        ElseIf ComboBox2.SelectedItem = "Dişli" Then
                    '            Image1.Image = picture13
                    '        End If
                    '    Case "300 [mm]"
                    '        If ComboBox2.SelectedItem = "Boş" Then
                    '            Image1.Image = picture32
                    '        ElseIf ComboBox2.SelectedItem = "Dişli" Then
                    '            Image1.Image = picture14
                    '        End If
                    '    Case "350 [mm]"
                    '        If ComboBox2.SelectedItem = "Boş" Then
                    '            Image1.Image = picture33
                    '        ElseIf ComboBox2.SelectedItem = "Dişli" Then
                    '            Image1.Image = picture15
                    '        End If
                    '    Case "400 [mm]"
                    '        If ComboBox2.SelectedItem = "Boş" Then
                    '            Image1.Image = picture25
                    '        ElseIf ComboBox2.SelectedItem = "Dişli" Then
                    '            Image1.Image = picture16
                    '        End If
                    '    Case "450 [mm]"
                    '        If ComboBox2.SelectedItem = "Boş" Then
                    '            Image1.Image = picture35
                    '        ElseIf ComboBox2.SelectedItem = "Dişli" Then
                    '            Image1.Image = picture17
                    '        End If
                    '    Case "500 [mm]"
                    '        If ComboBox2.SelectedItem = "Boş" Then
                    '            Image1.Image = picture36
                    '        ElseIf ComboBox2.SelectedItem = "Dişli" Then
                    '            Image1.Image = picture18
                End If
                'End Select
            End With
        Catch ex As Exception

        End Try
    End Sub
    Private Sub ComboBox3_SelectedIndexChanged(sender As Object, e As EventArgs) Handles ComboBox3.SelectedIndexChanged
        Try
            Dim picture1 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\10_STOOL\3D\1000_JW_STOOL_H100\1000.png") '1
            'Dim picture2 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\10_STOOL\3D\1001_JW_STOOL_H150\1001.png") '2
            'Dim picture3 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\10_STOOL\3D\1002_JW_STOOL_H200\1002.png") '3
            'Dim picture4 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\10_STOOL\3D\1003_JW_STOOL_H250\1003.png") '4
            'Dim picture5 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\10_STOOL\3D\1004_JW_STOOL_H300\1004.png") '5
            'Dim picture6 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\10_STOOL\3D\1005_JW_STOOL_H350\1005.png") '6
            'Dim picture7 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\10_STOOL\3D\1006_JW_STOOL_H400\1006.png") '7
            'Dim picture8 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\10_STOOL\3D\1007_JW_STOOL_H450\1007.png") '8
            'Dim picture9 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\10_STOOL\3D\1008_JW_STOOL_H500\1008.png") '9
            Dim picture10 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\11_STOOL_avec_isolation\3D\1100_JW_STOOL_H100\1100.png") '10
            'Dim picture11 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\11_STOOL_avec_isolation\3D\1100_JW_STOOL_H100\1101.png") '11
            'Dim picture12 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\11_STOOL_avec_isolation\3D\1100_JW_STOOL_H100\1102.png") '12
            'Dim picture13 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\11_STOOL_avec_isolation\3D\1100_JW_STOOL_H100\1103.png") '13
            'Dim picture14 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\11_STOOL_avec_isolation\3D\1100_JW_STOOL_H100\1104.png") '14
            'Dim picture15 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\11_STOOL_avec_isolation\3D\1100_JW_STOOL_H100\1105.png") '15
            'Dim picture16 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\11_STOOL_avec_isolation\3D\1100_JW_STOOL_H100\1106.png") '16
            'Dim picture17 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\11_STOOL_avec_isolation\3D\1100_JW_STOOL_H100\1107.png") '17
            'Dim picture18 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\11_STOOL_avec_isolation\3D\1100_JW_STOOL_H100\1108.png") '18
            Dim picture19 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\12_STOOL_sans_thread\3D\1200_JW_STOOL_H100\1200.png") '19
            'Dim picture20 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\12_STOOL_sans_thread\3D\1200_JW_STOOL_H100\1201.png") '20
            'Dim picture21 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\12_STOOL_sans_thread\3D\1200_JW_STOOL_H100\1202.png") '21
            'Dim picture22 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\12_STOOL_sans_thread\3D\1200_JW_STOOL_H100\1203.png") '22
            'Dim picture23 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\12_STOOL_sans_thread\3D\1200_JW_STOOL_H100\1204.png") '23
            'Dim picture24 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\12_STOOL_sans_thread\3D\1200_JW_STOOL_H100\1205.png") '24
            'Dim picture25 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\12_STOOL_sans_thread\3D\1200_JW_STOOL_H100\1206.png") '25
            'Dim picture26 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\12_STOOL_sans_thread\3D\1200_JW_STOOL_H100\1207.png") '26
            'Dim picture27 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\12_STOOL_sans_thread\3D\1200_JW_STOOL_H100\1208.png") '27
            Dim picture28 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\13_STOOL_avec_isolation_sans_thread\3D\1300_JW_STOOL_H100\1300.png") '28
            'Dim picture29 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\13_STOOL_avec_isolation_sans_thread\3D\1300_JW_STOOL_H100\1301.png") '29
            'Dim picture30 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\13_STOOL_avec_isolation_sans_thread\3D\1300_JW_STOOL_H100\1302.png") '30
            'Dim picture31 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\13_STOOL_avec_isolation_sans_thread\3D\1300_JW_STOOL_H100\1303.png") '31
            'Dim picture32 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\13_STOOL_avec_isolation_sans_thread\3D\1300_JW_STOOL_H100\1304.png") '32
            'Dim picture33 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\13_STOOL_avec_isolation_sans_thread\3D\1300_JW_STOOL_H100\1305.png") '33
            'Dim picture34 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\13_STOOL_avec_isolation_sans_thread\3D\1300_JW_STOOL_H100\1306.png") '34
            'Dim picture35 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\13_STOOL_avec_isolation_sans_thread\3D\1300_JW_STOOL_H100\1307.png") '35
            'Dim picture36 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\13_STOOL_avec_isolation_sans_thread\3D\1300_JW_STOOL_H100\1308.png") '36
            'Dim picture37 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\20_PACK ISOLATION_insulation set\3D\ISOLATION_POTEAU.png") '37
            'Dim picture38 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\12_STOOL_sans_thread.jpg") '38
            'Dim picture37 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\20_PACK ISOLATION_insulation set\3D\ISOLATION_POTEAU.png") '37
            ' Dim picture38 As Image = Image.FromFile("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\12_STOOL_sans_thread.jpg") '38
            ComboBox3.Focus()
            With Me.ComboBox3
                'Select Case ComboBox1.SelectedItem
                'Case "100 [mm]"
                If ComboBox2.SelectedItem = "Boş" Then
                    If ComboBox3.SelectedItem = "Var" Then
                        Image1.Image = picture28
                    Else
                        Image1.Image = picture19
                    End If
                ElseIf ComboBox2.SelectedItem = "Dişli" Then
                    If ComboBox3.SelectedItem = "Var" Then
                        Image1.Image = picture10
                    Else
                        Image1.Image = picture1
                    End If
                End If
                'Case "150 [mm]"
                '    If ComboBox2.SelectedItem = "Boş" Then
                '        If ComboBox3.SelectedItem = "Var" Then
                '            Image1.Image = picture29
                '        Else
                '            Image1.Image = picture20
                '        End If
                '    ElseIf ComboBox2.SelectedItem = "Dişli" Then
                '        If ComboBox3.SelectedItem = "Var" Then
                '            Image1.Image = picture11
                '        Else
                '            Image1.Image = picture2
                '        End If
                '    End If

                'Case "200 [mm]"
                '    If ComboBox2.SelectedItem = "Boş" Then
                '        If ComboBox3.SelectedItem = "Var" Then
                '            Image1.Image = picture30
                '        Else
                '            Image1.Image = picture21
                '        End If
                '    ElseIf ComboBox2.SelectedItem = "Dişli" Then
                '        If ComboBox3.SelectedItem = "Var" Then
                '            Image1.Image = picture12
                '        Else
                '            Image1.Image = picture3
                '        End If
                '    End If
                'Case "250 [mm]"
                '    If ComboBox2.SelectedItem = "Boş" Then
                '        If ComboBox3.SelectedItem = "Var" Then
                '            Image1.Image = picture31
                '        Else
                '            Image1.Image = picture22
                '        End If
                '    ElseIf ComboBox2.SelectedItem = "Dişli" Then
                '        If ComboBox3.SelectedItem = "Var" Then
                '            Image1.Image = picture13
                '        Else
                '            Image1.Image = picture4
                '        End If
                '    End If
                'Case "300 [mm]"
                '    If ComboBox2.SelectedItem = "Boş" Then
                '        If ComboBox3.SelectedItem = "Var" Then
                '            Image1.Image = picture32
                '        Else
                '            Image1.Image = picture23
                '        End If
                '    ElseIf ComboBox2.SelectedItem = "Dişli" Then
                '        If ComboBox3.SelectedItem = "Var" Then
                '            Image1.Image = picture14
                '        Else
                '            Image1.Image = picture5
                '        End If
                '    End If
                'Case "350 [mm]"
                '    If ComboBox2.SelectedItem = "Boş" Then
                '        If ComboBox3.SelectedItem = "Var" Then
                '            Image1.Image = picture33
                '        Else
                '            Image1.Image = picture24
                '        End If
                '    ElseIf ComboBox2.SelectedItem = "Dişli" Then
                '        If ComboBox3.SelectedItem = "Var" Then
                '            Image1.Image = picture15
                '        Else
                '            Image1.Image = picture6
                '        End If
                '    End If
                'Case "400 [mm]"
                '    If ComboBox2.SelectedItem = "Boş" Then
                '        If ComboBox3.SelectedItem = "Var" Then
                '            Image1.Image = picture34
                '        Else
                '            Image1.Image = picture25
                '        End If
                '    ElseIf ComboBox2.SelectedItem = "Dişli" Then
                '        If ComboBox3.SelectedItem = "Var" Then
                '            Image1.Image = picture16
                '        Else
                '            Image1.Image = picture7
                '        End If
                '    End If
                'Case "450 [mm]"
                '    If ComboBox2.SelectedItem = "Boş" Then
                '        If ComboBox3.SelectedItem = "Var" Then
                '            Image1.Image = picture35
                '        Else
                '            Image1.Image = picture26
                '        End If
                '    ElseIf ComboBox2.SelectedItem = "Dişli" Then
                '        If ComboBox3.SelectedItem = "Var" Then
                '            Image1.Image = picture17
                '        Else
                '            Image1.Image = picture8
                '        End If
                '    End If
                'Case "500 [mm]"
                '    If ComboBox2.SelectedItem = "Boş" Then
                '        If ComboBox3.SelectedItem = "Var" Then
                '            Image1.Image = picture36
                '        Else
                '            Image1.Image = picture27
                '        End If
                '    ElseIf ComboBox2.SelectedItem = "Dişli" Then
                '        If ComboBox3.SelectedItem = "Var" Then
                '            Image1.Image = picture18
                '        Else
                '            Image1.Image = picture9
                '        End If

                'End Select
            End With
        Catch ex As Exception

        End Try
    End Sub

    Private Sub Button1_Click(sender As Object, e As EventArgs) Handles Button1.Click
        Dim CATIA As Object
        Dim Mydocument
        Dim PartFactory
        Dim iPartDoc
        Select Case ComboBox1.SelectedItem
            Case "100 [mm]"
                If ComboBox2.SelectedItem = "Boş" Then
                    If ComboBox3.SelectedItem = "Var" Then
                        'Get CATIA or Launch it if necessary.
                        On Error Resume Next
                        CATIA = GetObject(, "CATIA.Application")

                        CATIA = CreateObject("CATIA.Application")
                        CATIA.Visible = True
                        iPartDoc = CATIA.Documents.Open("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\13_STOOL_avec_isolation_sans_thread\3D\1300_JW_STOOL_H100\1300_STOOL_H_100_.CATProduct")

                        On Error GoTo 0
                        ' Add a new Part


                        'PartFactory = Mydocument.Part.ShapeFactory  ' Retrieve the Part Factory.

                    Else
                        'Get CATIA or Launch it if necessary.
                        On Error Resume Next
                        CATIA = GetObject(, "CATIA.Application")

                        CATIA = CreateObject("CATIA.Application")
                        CATIA.Visible = True
                        iPartDoc = CATIA.Documents.Open("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\12_STOOL_sans_thread\3D\1200_JW_STOOL_H100\1200_STOOL_H_100_.CATProduct")

                        On Error GoTo 0
                        ' Add a new Part


                        'PartFactory = Mydocument.Part.ShapeFactory  ' Retrieve the Part Factory.

                    End If
                ElseIf ComboBox2.SelectedItem = "Dişli" Then
                    If ComboBox3.SelectedItem = "Var" Then
                        'Get CATIA or Launch it if necessary.
                        On Error Resume Next
                        CATIA = GetObject(, "CATIA.Application")

                        CATIA = CreateObject("CATIA.Application")
                        CATIA.Visible = True
                        iPartDoc = CATIA.Documents.Open("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\11_STOOL_avec_isolation\3D\1100_JW_STOOL_H100\1100_STOOL_H_100_.CATProduct")

                        On Error GoTo 0
                        ' Add a new Part


                        'PartFactory = Mydocument.Part.ShapeFactory  ' Retrieve the Part Factory.

                    Else
                        'Get CATIA or Launch it if necessary.
                        On Error Resume Next
                        CATIA = GetObject(, "CATIA.Application")

                        CATIA = CreateObject("CATIA.Application")
                        CATIA.Visible = True
                        iPartDoc = CATIA.Documents.Open("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\10_STOOL\3D\1000_JW_STOOL_H100\1000_STOOL_H_100_.CATProduct")

                        On Error GoTo 0
                        ' Add a new Part


                        'PartFactory = Mydocument.Part.ShapeFactory  ' Retrieve the Part Factory.

                    End If
                End If
            Case "150 [mm]"
                If ComboBox2.SelectedItem = "Boş" Then
                    If ComboBox3.SelectedItem = "Var" Then
                        'Get CATIA or Launch it if necessary.
                        On Error Resume Next
                        CATIA = GetObject(, "CATIA.Application")

                        CATIA = CreateObject("CATIA.Application")
                        CATIA.Visible = True
                        iPartDoc = CATIA.Documents.Open("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\13_STOOL_avec_isolation_sans_thread\3D\1301_JW_STOOL_H150\1301_STOOL_H_150_.CATProduct")

                        On Error GoTo 0
                        ' Add a new Part


                        'PartFactory = Mydocument.Part.ShapeFactory  ' Retrieve the Part Factory.

                    Else
                        'Get CATIA or Launch it if necessary.
                        On Error Resume Next
                        CATIA = GetObject(, "CATIA.Application")

                        CATIA = CreateObject("CATIA.Application")
                        CATIA.Visible = True
                        iPartDoc = CATIA.Documents.Open("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\12_STOOL_sans_thread\3D\1201_JW_STOOL_H150\1201_STOOL_H_150_.CATProduct")

                        On Error GoTo 0
                        ' Add a new Part


                        'PartFactory = Mydocument.Part.ShapeFactory  ' Retrieve the Part Factory.


                    End If
                ElseIf ComboBox2.SelectedItem = "Dişli" Then
                    If ComboBox3.SelectedItem = "Var" Then
                        'Get CATIA or Launch it if necessary.
                        On Error Resume Next
                        CATIA = GetObject(, "CATIA.Application")

                        CATIA = CreateObject("CATIA.Application")
                        CATIA.Visible = True
                        iPartDoc = CATIA.Documents.Open("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\11_STOOL_avec_isolation\3D\1101_JW_STOOL_H150\1101_STOOL_H_150_.CATProduct")

                        On Error GoTo 0
                        ' Add a new Part


                        'PartFactory = Mydocument.Part.ShapeFactory  ' Retrieve the Part Factory.

                    Else
                        'Get CATIA or Launch it if necessary.
                        On Error Resume Next
                        CATIA = GetObject(, "CATIA.Application")

                        CATIA = CreateObject("CATIA.Application")
                        CATIA.Visible = True
                        iPartDoc = CATIA.Documents.Open("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\10_STOOL\3D\1001_JW_STOOL_H150\1001_STOOL_H_150_.CATProduct")

                        On Error GoTo 0
                        ' Add a new Part


                        'PartFactory = Mydocument.Part.ShapeFactory  ' Retrieve the Part Factory.

                    End If
                End If

            Case "200 [mm]"
                If ComboBox2.SelectedItem = "Boş" Then
                    If ComboBox3.SelectedItem = "Var" Then
                        'Get CATIA or Launch it if necessary.
                        On Error Resume Next
                        CATIA = GetObject(, "CATIA.Application")

                        CATIA = CreateObject("CATIA.Application")
                        CATIA.Visible = True
                        iPartDoc = CATIA.Documents.Open("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\13_STOOL_avec_isolation_sans_thread\3D\1302_JW_STOOL_H200\1302_STOOL_H_200_.CATProduct")

                        On Error GoTo 0
                        ' Add a new Part


                        'PartFactory = Mydocument.Part.ShapeFactory  ' Retrieve the Part Factory.

                    Else
                        'Get CATIA or Launch it if necessary.
                        On Error Resume Next
                        CATIA = GetObject(, "CATIA.Application")

                        CATIA = CreateObject("CATIA.Application")
                        CATIA.Visible = True
                        iPartDoc = CATIA.Documents.Open("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\12_STOOL_sans_thread\3D\1202_JW_STOOL_H200\1202_STOOL_H_200_.CATProduct")

                        On Error GoTo 0
                        ' Add a new Part


                        'PartFactory = Mydocument.Part.ShapeFactory  ' Retrieve the Part Factory.

                    End If
                ElseIf ComboBox2.SelectedItem = "Dişli" Then
                    If ComboBox3.SelectedItem = "Var" Then
                        'Get CATIA or Launch it if necessary.
                        On Error Resume Next
                        CATIA = GetObject(, "CATIA.Application")

                        CATIA = CreateObject("CATIA.Application")
                        CATIA.Visible = True
                        iPartDoc = CATIA.Documents.Open("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\11_STOOL_avec_isolation\3D\1102_JW_STOOL_H200\1102_STOOL_H_200_.CATProduct")

                        On Error GoTo 0
                        ' Add a new Part


                        'PartFactory = Mydocument.Part.ShapeFactory  ' Retrieve the Part Factory.

                    Else
                        'Get CATIA or Launch it if necessary.
                        On Error Resume Next
                        CATIA = GetObject(, "CATIA.Application")

                        CATIA = CreateObject("CATIA.Application")
                        CATIA.Visible = True
                        iPartDoc = CATIA.Documents.Open("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\10_STOOL\3D\1002_JW_STOOL_H200\1002_STOOL_H_200_.CATProduct")

                        On Error GoTo 0
                        ' Add a new Part


                        'PartFactory = Mydocument.Part.ShapeFactory  ' Retrieve the Part Factory.

                    End If
                End If
            Case "250 [mm]"
                If ComboBox2.SelectedItem = "Boş" Then
                    If ComboBox3.SelectedItem = "Var" Then
                        'Get CATIA or Launch it if necessary.
                        On Error Resume Next
                        CATIA = GetObject(, "CATIA.Application")

                        CATIA = CreateObject("CATIA.Application")
                        CATIA.Visible = True
                        iPartDoc = CATIA.Documents.Open("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\13_STOOL_avec_isolation_sans_thread\3D\1303_JW_STOOL_H250\1303_STOOL_H_250_.CATProduct")

                        On Error GoTo 0
                        ' Add a new Part


                        'PartFactory = Mydocument.Part.ShapeFactory  ' Retrieve the Part Factory.

                    Else
                        'Get CATIA or Launch it if necessary.
                        On Error Resume Next
                        CATIA = GetObject(, "CATIA.Application")

                        CATIA = CreateObject("CATIA.Application")
                        CATIA.Visible = True
                        iPartDoc = CATIA.Documents.Open("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\12_STOOL_sans_thread\3D\1203_JW_STOOL_H250\1203_STOOL_H_250_.CATProduct")

                        On Error GoTo 0
                        ' Add a new Part


                        'PartFactory = Mydocument.Part.ShapeFactory  ' Retrieve the Part Factory.

                    End If
                ElseIf ComboBox2.SelectedItem = "Dişli" Then
                    If ComboBox3.SelectedItem = "Var" Then
                        'Get CATIA or Launch it if necessary.
                        On Error Resume Next
                        CATIA = GetObject(, "CATIA.Application")

                        CATIA = CreateObject("CATIA.Application")
                        CATIA.Visible = True
                        iPartDoc = CATIA.Documents.Open("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\11_STOOL_avec_isolation\3D\1103_JW_STOOL_H250\1103_STOOL_H_250_.CATProduct")

                        On Error GoTo 0
                        ' Add a new Part


                        'PartFactory = Mydocument.Part.ShapeFactory  ' Retrieve the Part Factory.

                    Else
                        'Get CATIA or Launch it if necessary.
                        On Error Resume Next
                        CATIA = GetObject(, "CATIA.Application")

                        CATIA = CreateObject("CATIA.Application")
                        CATIA.Visible = True
                        iPartDoc = CATIA.Documents.Open("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\10_STOOL\3D\1003_JW_STOOL_H250\1003_STOOL_H_250_.CATProduct")

                        On Error GoTo 0
                        ' Add a new Part


                        'PartFactory = Mydocument.Part.ShapeFactory  ' Retrieve the Part Factory.

                    End If
                End If
            Case "300 [mm]"
                If ComboBox2.SelectedItem = "Boş" Then
                    If ComboBox3.SelectedItem = "Var" Then
                        'Get CATIA or Launch it if necessary.
                        On Error Resume Next
                        CATIA = GetObject(, "CATIA.Application")

                        CATIA = CreateObject("CATIA.Application")
                        CATIA.Visible = True
                        iPartDoc = CATIA.Documents.Open("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\13_STOOL_avec_isolation_sans_thread\3D\1304_JW_STOOL_H300\1304_STOOL_H_300_.CATProduct")

                        On Error GoTo 0
                        ' Add a new Part


                        'PartFactory = Mydocument.Part.ShapeFactory  ' Retrieve the Part Factory.

                    Else
                        'Get CATIA or Launch it if necessary.
                        On Error Resume Next
                        CATIA = GetObject(, "CATIA.Application")

                        CATIA = CreateObject("CATIA.Application")
                        CATIA.Visible = True
                        iPartDoc = CATIA.Documents.Open("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\12_STOOL_sans_thread\3D\1204_JW_STOOL_H300\1204_STOOL_H_300_.CATProduct")

                        On Error GoTo 0
                        ' Add a new Part


                        'PartFactory = Mydocument.Part.ShapeFactory  ' Retrieve the Part Factory.

                    End If
                ElseIf ComboBox2.SelectedItem = "Dişli" Then
                    If ComboBox3.SelectedItem = "Var" Then
                        'Get CATIA or Launch it if necessary.
                        On Error Resume Next
                        CATIA = GetObject(, "CATIA.Application")

                        CATIA = CreateObject("CATIA.Application")
                        CATIA.Visible = True
                        iPartDoc = CATIA.Documents.Open("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\11_STOOL_avec_isolation\3D\1104_JW_STOOL_H300\1104_STOOL_H_300_.CATProduct")

                        On Error GoTo 0
                        ' Add a new Part


                        'PartFactory = Mydocument.Part.ShapeFactory  ' Retrieve the Part Factory.

                    Else
                        'Get CATIA or Launch it if necessary.
                        On Error Resume Next
                        CATIA = GetObject(, "CATIA.Application")

                        CATIA = CreateObject("CATIA.Application")
                        CATIA.Visible = True
                        iPartDoc = CATIA.Documents.Open("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\10_STOOL\3D\1004_JW_STOOL_H300\1004_STOOL_H_300_.CATProduct")

                        On Error GoTo 0
                        ' Add a new Part


                        'PartFactory = Mydocument.Part.ShapeFactory  ' Retrieve the Part Factory.

                    End If
                End If
            Case "350 [mm]"
                If ComboBox2.SelectedItem = "Boş" Then
                    If ComboBox3.SelectedItem = "Var" Then
                        'Get CATIA or Launch it if necessary.
                        On Error Resume Next
                        CATIA = GetObject(, "CATIA.Application")

                        CATIA = CreateObject("CATIA.Application")
                        CATIA.Visible = True
                        iPartDoc = CATIA.Documents.Open("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\13_STOOL_avec_isolation_sans_thread\3D\1305_JW_STOOL_H350\1305_STOOL_H_350_.CATProduct")

                        On Error GoTo 0
                        ' Add a new Part


                        'PartFactory = Mydocument.Part.ShapeFactory  ' Retrieve the Part Factory.

                    Else
                        'Get CATIA or Launch it if necessary.
                        On Error Resume Next
                        CATIA = GetObject(, "CATIA.Application")

                        CATIA = CreateObject("CATIA.Application")
                        CATIA.Visible = True
                        iPartDoc = CATIA.Documents.Open("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\12_STOOL_sans_thread\3D\1205_JW_STOOL_H350\1205_STOOL_H_350_.CATProduct")

                        On Error GoTo 0
                        ' Add a new Part


                        'PartFactory = Mydocument.Part.ShapeFactory  ' Retrieve the Part Factory.

                    End If
                ElseIf ComboBox2.SelectedItem = "Dişli" Then
                    If ComboBox3.SelectedItem = "Var" Then
                        'Get CATIA or Launch it if necessary.
                        On Error Resume Next
                        CATIA = GetObject(, "CATIA.Application")

                        CATIA = CreateObject("CATIA.Application")
                        CATIA.Visible = True
                        iPartDoc = CATIA.Documents.Open("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\11_STOOL_avec_isolation\3D\1105_JW_STOOL_H350\1105_STOOL_H_350_.CATProduct")

                        On Error GoTo 0
                        ' Add a new Part


                        'PartFactory = Mydocument.Part.ShapeFactory  ' Retrieve the Part Factory.

                    Else
                        'Get CATIA or Launch it if necessary.
                        On Error Resume Next
                        CATIA = GetObject(, "CATIA.Application")

                        CATIA = CreateObject("CATIA.Application")
                        CATIA.Visible = True
                        iPartDoc = CATIA.Documents.Open("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\10_STOOL\3D\1005_JW_STOOL_H350\1005_STOOL_H_350_.CATProduct")

                        On Error GoTo 0
                        ' Add a new Part


                        'PartFactory = Mydocument.Part.ShapeFactory  ' Retrieve the Part Factory.

                    End If
                End If
            Case "400 [mm]"
                If ComboBox2.SelectedItem = "Boş" Then
                    If ComboBox3.SelectedItem = "Var" Then
                        'Get CATIA or Launch it if necessary.
                        On Error Resume Next
                        CATIA = GetObject(, "CATIA.Application")

                        CATIA = CreateObject("CATIA.Application")
                        CATIA.Visible = True
                        iPartDoc = CATIA.Documents.Open("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\13_STOOL_avec_isolation_sans_thread\3D\1306_JW_STOOL_H400\1306_STOOL_H_400_.CATProduct")

                        On Error GoTo 0
                        ' Add a new Part


                        'PartFactory = Mydocument.Part.ShapeFactory  ' Retrieve the Part Factory.

                    Else
                        'Get CATIA or Launch it if necessary.
                        On Error Resume Next
                        CATIA = GetObject(, "CATIA.Application")

                        CATIA = CreateObject("CATIA.Application")
                        CATIA.Visible = True
                        iPartDoc = CATIA.Documents.Open("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\12_STOOL_sans_thread\3D\1206_JW_STOOL_H400\1206_STOOL_H_400_.CATProduct")

                        On Error GoTo 0
                        ' Add a new Part


                        'PartFactory = Mydocument.Part.ShapeFactory  ' Retrieve the Part Factory.

                    End If
                ElseIf ComboBox2.SelectedItem = "Dişli" Then
                    If ComboBox3.SelectedItem = "Var" Then
                        'Get CATIA or Launch it if necessary.
                        On Error Resume Next
                        CATIA = GetObject(, "CATIA.Application")

                        CATIA = CreateObject("CATIA.Application")
                        CATIA.Visible = True
                        On Error GoTo 0
                        ' Add a new Part


                        'PartFactory = Mydocument.Part.ShapeFactory  ' Retrieve the Part Factory.

                        iPartDoc = CATIA.Documents.Open("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\11_STOOL_avec_isolation\3D\1106_JW_STOOL_H400\1106_STOOL_H_400_.CATProduct")
                    Else
                        'Get CATIA or Launch it if necessary.
                        On Error Resume Next
                        CATIA = GetObject(, "CATIA.Application")

                        CATIA = CreateObject("CATIA.Application")
                        CATIA.Visible = True
                        iPartDoc = CATIA.Documents.Open("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\10_STOOL\3D\1006_JW_STOOL_H400\1006_STOOL_H_400_.CATProduct")

                        On Error GoTo 0
                        ' Add a new Part


                        'PartFactory = Mydocument.Part.ShapeFactory  ' Retrieve the Part Factory.

                    End If
                End If
            Case "450 [mm]"
                If ComboBox2.SelectedItem = "Boş" Then
                    If ComboBox3.SelectedItem = "Var" Then
                        'Get CATIA or Launch it if necessary.
                        On Error Resume Next
                        CATIA = GetObject(, "CATIA.Application")

                        CATIA = CreateObject("CATIA.Application")
                        CATIA.Visible = True
                        iPartDoc = CATIA.Documents.Open("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\13_STOOL_avec_isolation_sans_thread\3D\1307_JW_STOOL_H450\1307_STOOL_H_450_.CATProduct")

                        On Error GoTo 0
                        ' Add a new Part


                        'PartFactory = Mydocument.Part.ShapeFactory  ' Retrieve the Part Factory.

                    Else
                        'Get CATIA or Launch it if necessary.
                        On Error Resume Next
                        CATIA = GetObject(, "CATIA.Application")

                        CATIA = CreateObject("CATIA.Application")
                        CATIA.Visible = True
                        iPartDoc = CATIA.Documents.Open("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\12_STOOL_sans_thread\3D\1207_JW_STOOL_H450\1207_STOOL_H_450_.CATProduct")

                        On Error GoTo 0
                        ' Add a new Part


                        'PartFactory = Mydocument.Part.ShapeFactory  ' Retrieve the Part Factory.

                    End If
                ElseIf ComboBox2.SelectedItem = "Dişli" Then
                    If ComboBox3.SelectedItem = "Var" Then
                        'Get CATIA or Launch it if necessary.
                        On Error Resume Next
                        CATIA = GetObject(, "CATIA.Application")

                        CATIA = CreateObject("CATIA.Application")
                        CATIA.Visible = True
                        iPartDoc = CATIA.Documents.Open("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\11_STOOL_avec_isolation\3D\1107_JW_STOOL_H450\1107_STOOL_H_450_.CATProduct")

                        On Error GoTo 0
                        ' Add a new Part


                        'PartFactory = Mydocument.Part.ShapeFactory  ' Retrieve the Part Factory.

                    Else
                        'Get CATIA or Launch it if necessary.
                        On Error Resume Next
                        CATIA = GetObject(, "CATIA.Application")

                        CATIA = CreateObject("CATIA.Application")
                        CATIA.Visible = True
                        iPartDoc = CATIA.Documents.Open("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\10_STOOL\3D\1007_JW_STOOL_H450\1007_STOOL_H_450_.CATProduct")

                        On Error GoTo 0
                        ' Add a new Part


                        'PartFactory = Mydocument.Part.ShapeFactory  ' Retrieve the Part Factory.

                    End If
                End If
            Case "500 [mm]"
                If ComboBox2.SelectedItem = "Boş" Then
                    If ComboBox3.SelectedItem = "Var" Then
                        'Get CATIA or Launch it if necessary.
                        On Error Resume Next
                        CATIA = GetObject(, "CATIA.Application")

                        CATIA = CreateObject("CATIA.Application")
                        CATIA.Visible = True
                        iPartDoc = CATIA.Documents.Open("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\13_STOOL_avec_isolation_sans_thread\3D\1308_JW_STOOL_H500\1308_STOOL_H_500_.CATProduct")

                        On Error GoTo 0
                        ' Add a new Part


                        'PartFactory = Mydocument.Part.ShapeFactory  ' Retrieve the Part Factory.

                    Else
                        'Get CATIA or Launch it if necessary.
                        On Error Resume Next
                        CATIA = GetObject(, "CATIA.Application")

                        CATIA = CreateObject("CATIA.Application")
                        CATIA.Visible = True
                        iPartDoc = CATIA.Documents.Open("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\12_STOOL_sans_thread\3D\1208_JW_STOOL_H500\1208_STOOL_H_500_.CATProduct")

                        On Error GoTo 0
                        ' Add a new Part


                        'PartFactory = Mydocument.Part.ShapeFactory  ' Retrieve the Part Factory.

                    End If
                ElseIf ComboBox2.SelectedItem = "Dişli" Then
                    If ComboBox3.SelectedItem = "Var" Then
                        'Get CATIA or Launch it if necessary.
                        On Error Resume Next
                        CATIA = GetObject(, "CATIA.Application")

                        CATIA = CreateObject("CATIA.Application")
                        CATIA.Visible = True
                        iPartDoc = CATIA.Documents.Open("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\11_STOOL_avec_isolation\3D\1108_JW_STOOL_H500\1108_STOOL_H_500_.CATProduct")

                        On Error GoTo 0
                        ' Add a new Part


                        'PartFactory = Mydocument.Part.ShapeFactory  ' Retrieve the Part Factory.

                    Else
                        'Get CATIA or Launch it if necessary.
                        On Error Resume Next
                        CATIA = GetObject(, "CATIA.Application")

                        CATIA = CreateObject("CATIA.Application")
                        CATIA.Visible = True
                        iPartDoc = CATIA.Documents.Open("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\10_STOOL\3D\1008_JW_STOOL_H500\1008_STOOL_H_500_.CATProduct")

                        On Error GoTo 0
                        ' Add a new Part


                        'PartFactory = Mydocument.Part.ShapeFactory  ' Retrieve the Part Factory.

                    End If
                End If
        End Select
    End Sub

    Private Sub Button2_Click(sender As Object, e As EventArgs) Handles Button2.Click
        Parcatipi.Show()
        Me.Close()
    End Sub

    Private Sub Poteau_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        For i As Integer = 100 To 500 Step 50
            ComboBox1.Items.Add(i.ToString & " [mm]")
        Next
        ComboBox2.Items.Add("Dişli")
        ComboBox2.Items.Add("Boş")
        ComboBox3.Items.Add("Var")
        ComboBox3.Items.Add("Yok")

    End Sub

    Private Sub Button5_Click(sender As Object, e As EventArgs) Handles Button5.Click
        RenaultStandardi.Show()
        Me.Close()
    End Sub

    Private Sub Button3_Click(sender As Object, e As EventArgs) Handles Button3.Click
        Dim CATIA As Object
        Dim Mydocument
        Dim PartFactory
        Dim iPartDoc
        'Get CATIA or Launch it if necessary.
        On Error Resume Next
        CATIA = GetObject(, "CATIA.Application")

        CATIA = CreateObject("CATIA.Application")
        CATIA.Visible = True
        iPartDoc = CATIA.Documents.Open("I:\_sharediao\DIV\tooling_ass_oyk\uet_tooling_oyk\ORTAK\UET_MEKANIK\19-)Catalogue\BIBLIOTHEQUE_2020\101_REMONTAGE_std_RENAULT\E11_01000_STOOL_poteau\20_PACK ISOLATION_insulation set\3D\ENS_ISOLATION_POTEAU.CATProduct")

        On Error GoTo 0
        ' Add a new Part


        'PartFactory = Mydocument.Part.ShapeFactory  ' Retrieve the Part Factory.

    End Sub
End Class
